Feature branch of Mint Signup Page
defoebrand/mint-signup pull request #1
Opened 2020-06-05 14:56 UTC by defoebrand

In this feature branch we created the entirety of our Inuit Mint Signup page.

It involved a header, a form, and a footer.

The form should have input tags matching their purposes and connect to their respective labels.

This HTML has been validated.

2020-06-06 00:34 UTC, voscarmv commented
Pull Request Under Review by Oscar Mier (TSE) 👨‍💻 🐦

2020-06-06 01:00 UTC, voscarmv commented on index.html
> +  <!--     <link href="styles/reset.css" rel="stylesheet" type="text/css">   use to erase preset styles as debug tool -->
Please remove all comments from your `index.html` file. This is required by Microverse to approve the project, and it makes your code look clean! ✨

2020-06-06 01:01 UTC, voscarmv commented on styles/style.css
> +/* HEADER SECTION */
Please remove all comments from your CSS code. This is required by Microverse to approve the project, and it makes your code look clean! ✨

2020-06-06 01:13 UTC, voscarmv requested changes
# Impressive work so far team 🧐 💻 

## However, there are still some changes required... 📝 

- Substitute all `id` styling attributes for `class` on your `html` tags.
- Use the semantic `<main>` tag to make your code more easily readable to `web crawlers` 🕷️ 🕸️ 

### Don't forget to check my comments on your code for further required changes 👀 

### And that's it! 😃 👍 Apply the changes and re-submit for review!

## Questions? Comments? Contact me on [twitter](www.twitter.com/voscarmv) or [LinkedIn](www.linkedin.com/in/oscar-mier) 🧑‍💻 🗨️ 🧑‍💻 

### Happy coding! 💻 ⌨️ 🧠

2020-06-08 08:52 UTC, defoebrand commented
all instances of ids have been replaced with classes and the form element has been wrapped in a main element.  all comments have been removed

2020-06-08 08:56 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 
Very impressive work so far everything in your project is perfect. The website looks exactly like the clone :+1: :+1: the commit messages are perfect :+1: the repo looks professional :+1:  However there is one thing that has prevented me from approving this project. Your HTML has failed to pass validation. Kindly fix the following errors :arrow_down: 
![validator-html](https://user-images.githubusercontent.com/32361963/84011425-c38d1d00-a97e-11ea-907e-44ea55808505.jpg)

And also the CSS file :arrow_down: 
![validator-css](https://user-images.githubusercontent.com/32361963/84011491-def82800-a97e-11ea-90df-fdcfdbcdd61e.jpg)

Kindly fix those errors and resubmit your project

**HAPPY CODING ** :computer:

2020-06-08 09:46 UTC, tiagoes commented
We correct the bugs presented in Html validator and in the Css lints

2020-06-09 08:49 UTC, defoebrand commented
Updated CSS to reflect needed changes

2020-06-09 10:08 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-09 10:10 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello @defoebrand and @tiagoes** 
Amazing job :clap: :clap: you have passed all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the master branch

Keep going like this,

Oscar Andrés Russi Porras

2020-06-09 10:34 UTC, merged